# Generated by Django 3.0.5 on 2021-07-15 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='None')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=10)),
                ('url', models.URLField()),
                ('is_rcmnded', models.BooleanField(default=False)),
                ('rcmnd_title', models.CharField(blank=True, max_length=30, null=True)),
                ('rcmnd_whom', models.TextField(blank=True, null=True)),
                ('rcmnd_introduction', models.TextField(blank=True, null=True)),
                ('rcmnd_body', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookThickness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thickness', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Letter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
                ('created_at', models.DateField()),
                ('is_hot', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='None')),
                ('key_line', models.CharField(max_length=100, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('tmi', models.TextField(blank=True, null=True)),
                ('footnote', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('keywords', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=30, null=True)),
                ('category', models.ManyToManyField(to='contents.Category')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='contents.Book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='rcmnd_thickness',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contents.BookThickness'),
        ),
    ]
