# Generated by Django 3.0.5 on 2022-01-31 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_review_url',
            field=models.URLField(null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=25)),
                ('body', models.TextField(blank=True)),
                ('this_cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='contents.Content')),
            ],
        ),
    ]
