# Generated by Django 3.0.5 on 2022-01-31 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_auto_20220131_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='book_review_url',
            new_name='review_url',
        ),
    ]
