# Generated by Django 3.0.5 on 2022-01-31 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0003_auto_20220131_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
