# Generated by Django 3.0.5 on 2022-03-02 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0005_auto_20220302_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='letter',
            name='is_hot',
            field=models.BooleanField(default=False),
        ),
    ]
