"""
Django settings for synergy_django project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY','=3ar=l#c3ppb*gt%b2cm_6m$n&w+!f)bgis)q84&xjk(n1j!+1')

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = True
DEBUG = bool(os.environ.get('DJANGO_DEBUG', True))

if DEBUG == True:
    ALLOWED_HOSTS = [
    '127.0.0.1',
    '.bookcake.shop',
    '.bookcake.herokuapp.com'
    ]
elif DEBUG == False:   
    ALLOWED_HOSTS = [
        # '.ec2-54-180-83-4.ap-northeast-2.compute.amazonaws.com',
        '.bookcake.shop',
        '127.0.0.1',
        '.bookcake.herokuapp.com'
    ]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'contents.apps.ContentsConfig',

    'corsheaders',
    'rest_framework',
    'django_summernote',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
	'django.middleware.common.CommonMiddleware',
]

ROOT_URLCONF = 'synergy_django.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'synergy_django.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases
'''
AWS EC2 쓸 때 사용했던 설정
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME' : 'bookcake_db', # DB 식별자랑 다름!! DB이름!!
        'USER' : 'ryan',
        'PASSWORD' : 'shris9494',
        'HOST' : 'bookcake-db-instance.cazdqbj5oijd.ap-northeast-2.rds.amazonaws.com',
        'PORT' : '3306',
        'OPTIONS' : {
            'init_command' : 'SET sql_mode="STRICT_TRANS_TABLES"'
        }
    }
}
'''

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         # 'NAME' : BASE_DIR / 'db.sqlite3', 어느 블로그에서 이렇게 하라고 했는데 에러남
#         # 'NAME' : BASE_DIR,
#         'NAME' : os.path.join(BASE_DIR, 'db.sqlite3')
#     }
# }

import dj_database_url

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'bookcake', # pgAdmin에서 설정한 DB이름
        'USER': 'postgres',
        'PASSWORD': 'shris9494', # pgAdmin에서 정한 패스워드
        'HOST': 'localhost',
        'PORT': '5432', # Postgres 디폴트
    }
}

# PRODUCTION
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql_psycopg2',
#         'NAME': 'd6mbbdav1j4l6k', 
#         'USER': 'nkipwytzpgijao',
#         'PASSWORD': 'd712a0eec104196bbe0a6d8759a1f7150076b4eb033857299f014b244e976e03',
#         'HOST': 'c2-52-202-152-4.compute-1.amazonaws.com',
#         'PORT': 5432, # Postgres 디폴트
#     }
# }

db_from_env = dj_database_url.config(conn_max_age=500)
DATABASES['default'].update(db_from_env)

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = (
    # os.path.join(BASE_DIR, 'assets'),
    # os.path.join(BASE_DIR, 'resources')
)

MEDIA_URL = 'media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')
'''
When debug option is enabled(DEBUG=True), DO NOT forget to add urlpatterns as shown below:

from django.conf import settings
from django.conf.urls.static import static

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

'''

SUMMERNOTE_THEME = 'bs4'
SUMMERNOTE_CONFIG = {
    
    'summernote': {
        'fontNames': ['NanumSquare'],
    },
}

## 어드민에서 Django-summernote를 쓸 때, 아래를 적어주지 않으면 
X_FRAME_OPTIONS = 'ALLOWALL'
XS_SHARING_ALLOWED_METHODS = ['POST','GET','OPTIONS', 'PUT', 'DELETE']
## Refused to display 'http://127.0.0.1:8000/summernote/editor/id_body/' in a frame because it set 'X-Frame-Options' to 'deny'.
## 라는 에러가 뜬다! 

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://localhost:5000",
    "https://www.bookcake.kr",
]